"""Initial schema with indexes

Revision ID: 7655f09c4dad
Revises: 
Create Date: 2025-11-24 16:01:15.686492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7655f09c4dad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subreddit', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='reddit_bot'
    )
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False, schema='reddit_bot')
    op.create_index('ix_posts_processed_created', 'posts', ['processed_at', 'created_at'], unique=False, schema='reddit_bot')
    op.create_index('ix_posts_subreddit_created', 'posts', ['subreddit', 'created_at'], unique=False, schema='reddit_bot')
    op.create_table('successful_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_text', sa.Text(), nullable=False),
    sa.Column('subreddit', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_text'),
    schema='reddit_bot'
    )
    op.create_index('ix_patterns_extracted_at', 'successful_patterns', ['extracted_at'], unique=False, schema='reddit_bot')
    op.create_index('ix_patterns_score', 'successful_patterns', ['score'], unique=False, schema='reddit_bot')
    op.create_index('ix_patterns_subreddit_score', 'successful_patterns', ['subreddit', 'score'], unique=False, schema='reddit_bot')
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('karma_score', sa.Integer(), nullable=False),
    sa.Column('reddit_comment_id', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('is_golden_example', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['reddit_bot.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_comment_id'),
    schema='reddit_bot'
    )
    op.create_index('ix_comments_golden_karma', 'comments', ['is_golden_example', 'karma_score'], unique=False, schema='reddit_bot')
    op.create_index('ix_comments_karma_score', 'comments', ['karma_score'], unique=False, schema='reddit_bot')
    op.create_index('ix_comments_post_status', 'comments', ['post_id', 'status'], unique=False, schema='reddit_bot')
    op.create_index('ix_comments_posted_at', 'comments', ['posted_at'], unique=False, schema='reddit_bot')
    op.create_index('ix_comments_status_karma', 'comments', ['status', 'karma_score'], unique=False, schema='reddit_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('successful_patterns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pattern_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subreddit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('successful_patterns_pkey'))
    )
    op.create_table('posts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subreddit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('karma_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reddit_comment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_golden_example', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('comments_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.drop_index('ix_comments_status_karma', table_name='comments', schema='reddit_bot')
    op.drop_index('ix_comments_posted_at', table_name='comments', schema='reddit_bot')
    op.drop_index('ix_comments_post_status', table_name='comments', schema='reddit_bot')
    op.drop_index('ix_comments_karma_score', table_name='comments', schema='reddit_bot')
    op.drop_index('ix_comments_golden_karma', table_name='comments', schema='reddit_bot')
    op.drop_table('comments', schema='reddit_bot')
    op.drop_index('ix_patterns_subreddit_score', table_name='successful_patterns', schema='reddit_bot')
    op.drop_index('ix_patterns_score', table_name='successful_patterns', schema='reddit_bot')
    op.drop_index('ix_patterns_extracted_at', table_name='successful_patterns', schema='reddit_bot')
    op.drop_table('successful_patterns', schema='reddit_bot')
    op.drop_index('ix_posts_subreddit_created', table_name='posts', schema='reddit_bot')
    op.drop_index('ix_posts_processed_created', table_name='posts', schema='reddit_bot')
    op.drop_index('ix_posts_created_at', table_name='posts', schema='reddit_bot')
    op.drop_table('posts', schema='reddit_bot')
    # ### end Alembic commands ###
