/**
 * Data fetching from static JSON (generated by Python script).
 * 
 * The JSON is generated during GitHub Actions build using:
 * uv run python scripts/generate_dashboard_data.py
 */

export interface DashboardStats {
  totalPosts: number
  totalComments: number
  postedComments: number
  pendingComments: number
  rejectedComments: number
  totalKarma: number
  avgKarma: number
  topSubreddits: { subreddit: string; count: number }[]
  recentActivity: { date: string; posts: number; comments: number }[]
  aiProviderUsage: { provider: string; count: number }[]
}

export interface Comment {
  id: string
  content: string
  status: 'pending' | 'approved' | 'rejected' | 'posted'
  karma_score: number | null
  ai_provider: string | null
  created_at: string | null
}

export interface DashboardData {
  generated_at: string
  stats: DashboardStats
  recentComments: Comment[]
}

// Demo data for when JSON doesn't exist
export const demoData: DashboardData = {
  generated_at: new Date().toISOString(),
  stats: {
    totalPosts: 156,
    totalComments: 89,
    postedComments: 67,
    pendingComments: 12,
    rejectedComments: 10,
    totalKarma: 1234,
    avgKarma: 18.4,
    topSubreddits: [
      { subreddit: 'AskReddit', count: 45 },
      { subreddit: 'NoStupidQuestions', count: 32 },
      { subreddit: 'explainlikeimfive', count: 28 },
      { subreddit: 'programming', count: 15 },
      { subreddit: 'webdev', count: 12 },
    ],
    recentActivity: [
      { date: '2025-11-24', posts: 12, comments: 8 },
      { date: '2025-11-25', posts: 18, comments: 14 },
      { date: '2025-11-26', posts: 15, comments: 11 },
      { date: '2025-11-27', posts: 22, comments: 16 },
      { date: '2025-11-28', posts: 19, comments: 13 },
      { date: '2025-11-29', posts: 25, comments: 18 },
      { date: '2025-11-30', posts: 28, comments: 21 },
    ],
    aiProviderUsage: [
      { provider: 'gemini-pro', count: 45 },
      { provider: 'gemini-flash', count: 32 },
      { provider: 'claude', count: 12 },
    ],
  },
  recentComments: [
    {
      id: '1',
      content: 'python. ngl i tried starting with something else and it was a nightmare of semicolons. python just lets you build stuff fast.',
      status: 'posted',
      karma_score: 42,
      ai_provider: 'gemini-pro',
      created_at: '2025-11-30T10:00:00Z',
    },
    {
      id: '2',
      content: "tbh i think it's because their work scales like crazy. one person can write a program that a million people use.",
      status: 'posted',
      karma_score: 28,
      ai_provider: 'gemini-pro',
      created_at: '2025-11-30T09:30:00Z',
    },
    {
      id: '3',
      content: "in software, when a manager asks for 'one tiny little change' it's almost never tiny lol",
      status: 'pending',
      karma_score: null,
      ai_provider: 'gemini-flash',
      created_at: '2025-11-30T08:00:00Z',
    },
  ],
}

/**
 * Fetch dashboard data from static JSON file.
 * Falls back to demo data if file doesn't exist.
 */
export async function fetchDashboardData(): Promise<{ data: DashboardData; isDemo: boolean }> {
  try {
    const response = await fetch('./data.json')
    
    if (!response.ok) {
      console.log('data.json not found, using demo data')
      return { data: demoData, isDemo: true }
    }
    
    const data: DashboardData = await response.json()
    return { data, isDemo: false }
  } catch (error) {
    console.error('Failed to fetch data.json:', error)
    return { data: demoData, isDemo: true }
  }
}

